# Generated by Django 4.1.3 on 2024-03-29 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contact_alter_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='nummer',
            new_name='number',
        ),
    ]
