# Generated by Django 4.1.3 on 2024-03-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy_and_ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('additional_information', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
