# Generated by Django 4.1.3 on 2024-03-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_buy_and_ship_delete_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_and_ship',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
